### ISSUE TITLE
User Story 6: advanced wheels

### ISSUE THREAD

**Issue by ChristophObst** [ChristophObst/Capstone-slot-machine#11]
## Value proposition

As a player
I want to see more symbols of the slot machine`s wheels at the same time.
So that I can try to predict the symbols next order while playing. 

## Description

![Image](https://user-images.githubusercontent.com/124210038/232007377-520abf9a-ce92-4cea-8077-bea4066d205f.png)

## Acceptance criteria

- [ ] 3x3 symbols  are implemented and visible
- [ ] the single slots repeat their symbols in the correct order (the symbols order never changes with RNG)
- [ ]  trys and win condition will be ignored/switched off/comment out in this user story and refactored on a later story.

## Tasks

- [ ] advance the "matchfield" (3x3 symbols at all)

**Comment by PReichetanz** [comment]
LGTM!
